baseURL = 'https://fathmubina.github.io/'
locale = 'en-us'
title = 'Fathan Mubina'

[params]
  favicon = "/favicon.png"
  [params.theme_config]
    appearance = "light"
    isShowFooter = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'
